

// Generated helper templates
// Generated items
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ARIClient.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\MailboxesActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\IMailboxesActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\Mailbox.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\RecordingsActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\IRecordingsActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\LiveRecording.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\StoredRecording.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\SoundsActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ISoundsActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\Sound.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\FormatLangPair.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\PlaybacksActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\IPlaybacksActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\Playback.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\DeviceStatesActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\IDeviceStatesActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\DeviceState.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\EndpointsActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\IEndpointsActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\TextMessage.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\TextMessageVariable.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\Endpoint.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ApplicationsActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\IApplicationsActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\Application.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\AsteriskActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\IAsteriskActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\Variable.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\AsteriskInfo.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\StatusInfo.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ConfigInfo.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\SetId.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\SystemInfo.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\BuildInfo.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelsActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\IChannelsActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\Channel.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\CallerID.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\DialplanCEP.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\Dialed.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\BridgesActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\IBridgesActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\Bridge.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\EventsActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\IEventsActions.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelConnectedLineEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\TextMessageReceivedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\StasisStartEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\StasisEndEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\DialEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\EndpointStateChangeEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelTalkingFinishedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelTalkingStartedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelVarsetEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelHangupRequestEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelUsereventEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelCallerIdEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelDialplanEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelDtmfReceivedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelStateChangeEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelLeftBridgeEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelEnteredBridgeEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelDestroyedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ChannelCreatedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\BridgeAttendedTransferEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\BridgeBlindTransferEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\BridgeMergedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\BridgeDestroyedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\BridgeCreatedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\ApplicationReplacedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\RecordingFailedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\RecordingFinishedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\RecordingStartedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\PlaybackFinishedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\PlaybackStartedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\DeviceStateChangedEvent.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\Event.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\MissingParams.cs
// C:\Source\github-repos\telzio\telzio\lib\asternet-ari\CodeGeneratror\ARICodeGen\Templates\Message.cs
